language: node_js
node_js: node
services: 
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: GNERNs77th+aP3fiJR6I4WjKV9RIHNWtAfn7X5d53bxOs0NnE36/gVZstz1XrlLin4PdO57CWQ6Py1/r4ivevAbIMRAJHewPqUAsB3xoSDCcOLfu7ib45BV1aMnw38c8q4KUxdAcSfYFoZl3gsp7TM31ctOW52RBi93jf1di4pUgLJyjjtReF1kYDGZYHrIm312bVQvnCKO5QqW4eyfPnF5/grfaiif+Q/tmcl4FzzCulL6VHTDkwunKKlzLksuj7GvfF5+t41EUD1v6LEdXAEUQZuKV4OPxr/9aYM/9jGRfKBeSedVZcWm7VBaMy9+GBQ9HUpzvXJfqku5D/CvDQ7UX87TVgOocicO6laNQCYfm2gxmOF8AhIDQ0LbL9sGGlFyunP/Wi+ohL35ooWa4XpWYevmnDXnnK4cikX1auuuM2DpXq4ychWSjK+QYVFOUIxfxYLZGn+zUcDEtafmmuo7hgRYNmeyy1fkVuhEQIXZ/t6au2MZxSKfSSAeW1pePip0acqvT+KKeMHeg7R4syr0SGG5Vq/QjdikRH3tFD5CoM8wo2cjNSpRUlc39L/Fbwqhgy0XTes1qBPSFLgWV2JrDPir3LrQyc1/zP9nWjw7mSDWIU3IUMjhDV3RM2bIqhLeb9Xq5jW2onUDzJiWSAqY0B2eflO46PFmPOQUKX+4=
  app: griot
  skip_cleanup: true
  on:
    repo: Simonmaxwell/Griot
